//
//  LoginRouter.swift
//  TodoListCS
//
//  Created by Антон Заричный on 21.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
	func routeToToDoListContoller(segue: UIStoryboardSegue?)
}

class LoginRouter: NSObject, LoginRoutingLogic {
	weak var viewController: LoginViewController?
	
	// MARK: Routing
	
	func routeToToDoListContoller(segue: UIStoryboardSegue?) {
		if let segue = segue {
			let destinationVC = segue.destination as! ToDoListViewController
		} else {
			let storyboard = UIStoryboard(name: "Main", bundle: nil)
			let destinationVC = storyboard.instantiateViewController(withIdentifier: "ToDoListViewController") as! ToDoListViewController
			navigateToToDoListController(source: viewController!, destination: destinationVC)
		}
	}
	
	// MARK: Navigation
	
	private func navigateToToDoListController(source: LoginViewController, destination: ToDoListViewController) {
		source.show(destination, sender: nil)
	}
}


